image: "cypress/browsers:chrome67"

stages:
  - build

docker_build:
  stage: build
  image: "docker:latest"
  services: ["docker:dind"]
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker build "$CI_PROJECT_DIR"
